name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: prateekgurnani10/prateekgurnani10@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
